# Profil dev — mvn quarkus:dev
quarkus:
  devservices:
    enabled: true
  log:
    level: INFO
    category:
      "com.nouraschool":
        level: DEBUG
      "org.hibernate.SQL":
        level: DEBUG
  swagger-ui:
    always-include: true
  http:
    port: 8080

# En dev : seed de données de test si vide (DataSeedRunner)
